import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Providers from './providers'
import ThemeBtn from './components/ThemeBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header>
            <nav className='flex justify-center gap-36 p-12'>
              <ul>
                <li>
                  <Link href='/'>Home</Link>
                </li>
              </ul>

              <ThemeBtn />
            </nav>
          </header>

          <main>{children}</main>

          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
